dist: trusty
sudo: required

env:
  - VERSION=$TRAVIS_COMMIT

before_script:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - make pull build 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin;
    make tag push;
    fi

notifications:
  slack: 
    rooms:
      secure: $SLACK_KUBERNIKUS 
