apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app: fluent-bit-fluent-bit
    release: fluent-bit
data:
  fluent-bit.conf: |-
      [SERVICE]
          Flush        1
          Daemon       Off
          Log_Level    info
          Parsers_File parsers.conf

      [INPUT]
          Name             tail
          Path             /var/log/containers/*.log
          Parser           docker
          Tag              kube.*
          Refresh_Interval 5
          Mem_Buf_Limit    5MB
          Skip_Long_Lines  Off

      [INPUT]
          Name          systemd
          Path          /var/log/journal
          Tag           systemd.*
          Mem_Buf_Limit 5MB

      [FILTER]
          Name          record_modifier
          Match         systemd.*
          Whitelist_key _SYSTEMD_UNIT
          Whitelist_key MESSAGE
          Whitelist_key _PID
          Whitelist_key _PRIORITY
          Whitelist_key _COMM
          Whitelist_key _HOSTNAME

      [FILTER]
          Name   modify
          Match  systemd.*
          Rename _SYSTEMD_UNIT unit
          Rename MESSAGE log
          Rename _PID pid
          Rename _PRIORITY priority
          Rename _COMM cmd
          Rename _HOSTNAME hostname

      [FILTER]
          Name       record_modifier
          Match      kube.*
          Remove_key time

      [FILTER]
          Name               kubernetes
          Match              kube.*
          Kube_URL           https://kubernetes.default.svc:443
          tls.verify         Off
          Kube_CA_File       /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token

{{ if index .Values "fluent-bit" "filter" "additionalValues" }}
      [FILTER]
          Name record_modifier
          Match *
{{- range index .Values "fluent-bit" "filter" "additionalValues" }}
          Record {{ .key }} {{ .value }}
{{- end }}
{{- end }}

      [OUTPUT]
          Name  es
          Match *
          Host  {{ index .Values "fluent-bit" "backend" "es" "host" }}
          Port  443
          Logstash_Format On
          Retry_Limit False
          Type  flb_type
          Time_Key @timestamp
          Logstash_Prefix kubernikus
          HTTP_User {{ index .Values "fluent-bit" "backend" "es" "http_user" }}
          HTTP_Passwd {{ index .Values "fluent-bit" "backend" "es" "http_passwd" }}
          tls on
          tls.verify on
          tls.debug 1
  parsers.conf: ""
