apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: kubernikus-prometheus

spec:
  replicas: 1 
  selector:
    matchLabels:
      tier: kubernikus
      app: prometheus
  template:
    metadata:
      labels:
        tier: kubernikus
        app: prometheus
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
        - name: prometheus 
          image: "{{.Values.prometheus.image}}:{{.Values.prometheus.tag}}"
          args:
            - --config.file=/etc/prometheus/prometheus.yaml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention={{.Values.retention}}
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.external-url=http://localhost:9090/prometheus
            - --log.level={{ default "info" .Values.log_level }}
          ports:
            - name: http 
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /prometheus
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name | quote }}
        - name: config
          configMap:
            name: kubernikus-prometheus

