apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: kubernikus-api

data:
  tls.crt: {{ default "" .Values.api.tls_crt | b64enc | quote }}
  tls.key: {{ default "" .Values.api.tls_key | b64enc | quote }}
