{{- if .Values.vice }}
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ template "name" . }}

data:
  vice.cert: {{ default "" .Values.vice.cert | b64enc | quote }}
  vice.key: {{ default "" .Values.vice.key | b64enc | quote }}
  intermediate.cert: {{ default "" .Values.vice.intermediate | b64enc | quote }}
{{- end }}
