imagesForVersion:
  '1.12.10':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.12.10'
  '1.11.9':
    default: true
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.11.9'
  '1.10.11':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.11'
  '1.10.8':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.8'
  '1.10.7':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.7'
  '1.10.1':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.1'
  '1.9.11':
    hyperkube:
      repository: 'quay.io/coreos/hyperkube'
      tag: 'v1.9.11_coreos.1'
  '1.9.0':
    hyperkube:
      repository: 'quay.io/coreos/hyperkube'
      tag: 'v1.9.0_coreos.0'
  '1.8.14':
    hyperkube: 
      repository: 'quay.io/coreos/hyperkube'
      tag: 'v1.8.14_coreos.1'
  '1.7.16':
    hyperkube:
      repository: 'quay.io/coreos/hyperkube'
      tag: 'v1.7.16_coreos.0'
  '1.7.5':
    hyperkube:
      repository: 'quay.io/coreos/hyperkube'
      tag: 'v1.7.5_coreos.0'
