imagesForVersion:
  '1.16.14':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.16.14'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.16.0'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
    dashboardProxy:
      repository: 'hub.global.cloud.sap/monsoon/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
  '1.16.9':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.16.9'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.16.0'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
    dashboardProxy:
      repository: 'hub.global.cloud.sap/monsoon/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
  '1.15.9':
    default: true
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.15.9'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.15.0-sap.2'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
    dashboardProxy:
      repository: 'hub.global.cloud.sap/monsoon/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
  '1.15.2':
    supported: false
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.15.2'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.15.0-sap.2'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
    dashboardProxy:
      repository: 'hub.global.cloud.sap/monsoon/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
  '1.14.5':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.14.5'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.14.0-sap.0'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
    dashboardProxy:
      repository: 'hub.global.cloud.sap/monsoon/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
  '1.13.9':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.13.9'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.13.1'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
    dashboardProxy:
      repository: 'hub.global.cloud.sap/monsoon/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
  '1.12.10':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.12.10'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
    dashboardProxy:
      repository: 'hub.global.cloud.sap/monsoon/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
  '1.11.9':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.11.9'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
    dashboardProxy:
      repository: 'hub.global.cloud.sap/monsoon/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'sapcc/kubernetes-dashboard-amd64'
      tag: 'v1.10.1'
  '1.10.11':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.11'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
  '1.10.8':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.8'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
  '1.10.7':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.7'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
  '1.10.1':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.1'
    dex:
      repository: 'hub.global.cloud.sap/monsoon/dex'
      tag: '8373c31b3e2d96ad3a7313227aa1bb8c59ddca39'
