imagesForVersion:
  '1.19.4':
    supported: true
    apiserver:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/kube-apiserver'
      tag: 'v1.19.4'
    controllerManager:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/kube-controller-manager'
      tag: 'v1.19.4'
    scheduler:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/kube-scheduler'
      tag: 'v1.19.4'
    kubelet:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/kubelet'
      tag: 'v1.19.4'
    kubeProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/kube-proxy'
      tag: 'v1.19.4'
    cloudControllerManager:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/openstack-cloud-controller-manager'
      tag: 'v1.19.2'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.4'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.18.10':
    supported: true
    hyperkube:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/hyperkube'
      tag: 'v1.18.10'
    cloudControllerManager:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/openstack-cloud-controller-manager'
      tag: 'v1.18.0'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.4'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.17.13':
    supported: true
    hyperkube:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/hyperkube'
      tag: 'v1.17.13'
    cloudControllerManager:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/openstack-cloud-controller-manager'
      tag: 'v1.17.0'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.4'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.16.14':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.16.14'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.16.0'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.16.9':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.16.9'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.16.0'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.15.9':
    default: true
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.15.9'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.15.0-sap.2'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.15.2':
    supported: false
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.15.2'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.15.0-sap.2'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.14.5':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.14.5'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.14.0-sap.0'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.13.9':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.13.9'
    cloudControllerManager:
      repository: 'sapcc/openstack-cloud-controller-manager'
      tag: 'v1.13.1'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
    coreDNS:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.12.10':
    supported: true
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.12.10'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
    pause:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
  '1.11.9':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.11.9'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'sapcc/kubernetes-dashboard-amd64'
      tag: 'v1.10.1'
  '1.10.11':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.11'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
  '1.10.8':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.8'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
  '1.10.7':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.7'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
  '1.10.1':
    hyperkube:
      repository: 'sapcc/hyperkube'
      tag: 'v1.10.1'
    dex:
      repository: 'keppel.eu-de-1.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
