imagesForVersion:
  '1.20.4':
    supported: true
    apiserver:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-apiserver'
      tag: 'v1.20.4'
    controllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-controller-manager'
      tag: 'v1.20.4'
    scheduler:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-scheduler'
      tag: 'v1.20.4'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    kubelet:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubelet'
      tag: 'v1.20.4'
    kubeProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-proxy'
      tag: 'v1.20.4'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud/openstack-cloud-controller-manager'
      tag: 'v1.20.1'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.4'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
    csiAttacher:
      repository: 'keppel.$REGION.cloud.sap/ccloud/csi-attacher'
      tag: 'v2.2.1'
    csiProvisioner:
      repository: 'keppel.$REGION.cloud.sap/ccloud/csi-provisioner'
      tag: 'v2.1.0'
    csiSnapshotter:
      repository: 'keppel.$REGION.cloud.sap/ccloud/csi-snapshotter'
      tag: 'v2.1.3'
    csiSnapshotController:
      repository: 'keppel.$REGION.cloud.sap/ccloud/csi-snapshot-controller'
      tag: 'v2.1.3'
    csiResizer:
      repository: 'keppel.$REGION.cloud.sap/ccloud/csi-resizer'
      tag: 'v0.5.1'
    csiLivenessProbe:
      repository: 'keppel.$REGION.cloud.sap/ccloud/csi-livenessprobe'
      tag: 'v2.1.0'
    csiNodeDriver:
      repository: 'keppel.$REGION.cloud.sap/ccloud/csi-node-driver-registrar'
      tag: 'v1.3.0'
    cinderCSIPlugin:
      repository: 'keppel.$REGION.cloud.sap/ccloud/cinder-csi-plugin'
      tag: 'v1.20.0'
    flannel:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-flannel'
      tag: 'v0.13.0'
  '1.19.4':
    supported: true
    apiserver:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-apiserver'
      tag: 'v1.19.4'
    controllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-controller-manager'
      tag: 'v1.19.4'
    scheduler:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-scheduler'
      tag: 'v1.19.4'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    kubelet:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubelet'
      tag: 'v1.19.4'
    kubeProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kube-proxy'
      tag: 'v1.19.4'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud/openstack-cloud-controller-manager'
      tag: 'v1.19.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.4'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.18.10':
    supported: true
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.18.10'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud/openstack-cloud-controller-manager'
      tag: 'v1.18.0'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.4'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.17.13':
    supported: true
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.17.13'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud/openstack-cloud-controller-manager'
      tag: 'v1.17.0'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.4'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.16.14':
    supported: true
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.16.14'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/openstack-cloud-controller-manager'
      tag: 'v1.16.0'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.16.9':
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.16.9'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/openstack-cloud-controller-manager'
      tag: 'v1.16.0'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.15.9':
    default: true
    supported: true
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.15.9'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/openstack-cloud-controller-manager'
      tag: 'v1.15.0-sap.2'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.15.2':
    supported: false
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.15.2'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/openstack-cloud-controller-manager'
      tag: 'v1.15.0-sap.2'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.0-beta4'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.14.5':
    supported: true
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.14.5'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/openstack-cloud-controller-manager'
      tag: 'v1.14.0-sap.0'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.13.9':
    supported: true
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.13.9'
    cloudControllerManager:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/openstack-cloud-controller-manager'
      tag: 'v1.13.1'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
    coreDNS:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/coredns'
      tag: '1.6.2'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.12.10':
    supported: true
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.12.10'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/kubernetesui/dashboard'
      tag: 'v2.0.0-beta1'
    pause:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/pause-amd64'
      tag: '3.1'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.11.9':
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.11.9'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    dashboardProxy:
      repository: 'keppel.$REGION.cloud.sap/ccloud/keycloak-gatekeeper'
      tag: '6.0.1'
    dashboard:
      repository: 'sapcc/kubernetes-dashboard-amd64'
      tag: 'v1.10.1'
    wormhole:
      repository: keppel.$REGION.cloud.sap/ccloud/kubernikus
      tag: 'changeme' #this is injected to match the operator so far
  '1.10.11':
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.10.11'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.10.7':
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.10.7'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
  '1.10.1':
    hyperkube:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/hyperkube'
      tag: 'v1.10.1'
    etcd:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcd'
      tag: 'v3.3.14'
    etcdBackup:
      repository: 'keppel.$REGION.cloud.sap/ccloud-dockerhub-mirror/sapcc/etcdbrctl'
      tag: '0.5.2'
    dex:
      repository: 'keppel.$REGION.cloud.sap/ccloud/dex'
      tag: '38f4f8ea8d487470a1dd5b83d66b428d8b502f81'
    wormhole:
      repository: 'keppel.$REGION.cloud.sap/ccloud/kubernikus'
      tag: 'changeme' #this is injected to match the operator so far
