image: "keppel.global.cloud.sap/ccloud/k8sniff"
tag: "edeab22b1f2209905923d553996648168ff40561"
metrics_port: 9091
log_level: 2
replicas: 2
useRBAC: false

service:
  type: LoadBalancer
  #nodePort:
  #loadBalancerIP:
  #externalIP:
