domain: xyz.com
bootstrapToken: xyz
nodePassword: xyz
secretName: test
openstack:
  authURL: http://xyz.com
  username: xyz
  password: xyz
  domainName: xyz.com
  lbSubnetID: xyz
  lbFloatingNetworkID: xyz
  routerID: xyz
  projectID: xy
  region: xy-xy-1
  projectDomainName: xyz
api:
  apiserverHost: xyz.com
  wormholeHost: xyz.com
version:
  kubernikus: xyz
  kubernetes: 1.0.0
etcd:
  backup:
    storageProvider: Swift
  secure:
    enabled: true
  openstack:
    authURL: http://xyz.com
    username: xyz
    password: xyz
    domainName: xyz.com
    projectID: xyz
imagesForVersion:
  "1.0.0":
    hyperkube:
      repository: abc
      tag: xyz
images:
  hyperkube:
    repository: abc
    tag: xyz
dashboard:
  enabled: false
dex:
  enabled: false
