{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "master.fullname" . }}
  labels:
    component: apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: apiserver
      port: {{ .Values.advertisePort }}
    - name: wormhole
      port: 6553
  selector:
    app: {{ include "master.fullname" . }}-apiserver
