dependencies:
  - name: vice-president 
    repository: file://vendor/vice-president
    version: 0.1.1
  - name: kube-state-metrics
    repository: file://vendor/kube-state-metrics
    version: 1.1.0
  - name: grafana 
    repository: https://raw.githubusercontent.com/BugRoger/charts/repo
    version: 0.6.2
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.9.4
