dependencies:
  - name: vice-president 
    repository: file://vendor/vice-president
    version: 0.1.3
  - name: kube-state-metrics
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.9.0
  - name: grafana 
    repository: https://raw.githubusercontent.com/BugRoger/charts/repo
    version: 0.6.2
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.9.4
  - name: prometheus-node-exporter
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.3.0
  - name: oomkill-exporter
    repository: file://vendor/oomkill-exporter
    version: 0.1.0
